spring:
  application:
    name: limiter
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8

server:
  port: 8080
